// Letterboxd "Latest Activity" micro-app
// This script reads the 'feed.json' file generated by the GitHub Action.

const MAX_ITEMS = 5;

const els = {
  q: document.getElementById("q"),
  status: document.getElementById("status"),
  results: document.getElementById("results"),
  empty: document.getElementById("empty"),
  pills: Array.from(document.querySelectorAll(".pill")),
};

let filter = "all"; 
let DATA = [];

function render(items) {
  els.results.innerHTML = "";
  if (items.length === 0) {
    els.results.hidden = true;
    els.empty.hidden = false;
    els.status.textContent = "0 results";
    return;
  }

  els.empty.hidden = true;
  els.results.hidden = false;
  els.status.textContent = `${items.length} item${items.length === 1 ? "" : "s"}`;

  for (const it of items) {
    const li = document.createElement("li");
    li.className = "item";
    li.innerHTML = `
      <p class="itemTitle">
        <a class="link" href="${it.link}" target="_blank" rel="noopener noreferrer">${it.title}</a>
        ${it.year ? `<span class="year">(${it.year})</span>` : ""}
      </p>
      <p class="itemMeta">
        ${it.rating ? `<span class="rating">${it.rating}</span>` : ""}
      </p>
    `;
    els.results.appendChild(li);
  }
}

function apply() {
  const q = (els.q.value || "").trim().toLowerCase();
  let items = DATA;

  // Simple filtering based on the search input
  if (q) {
    items = items.filter(d =>
      `${d.title} ${d.year}`.toLowerCase().includes(q)
    );
  }

  render(items.slice(0, MAX_ITEMS));
}

function setFilter(next) {
  filter = next;
  els.pills.forEach(p => p.classList.toggle("is-active", p.dataset.filter === next));
  apply();
}

async function loadFeed() {
  els.status.textContent = "Loading…";

  // Fetch the local JSON file created by the GitHub Action
  const res = await fetch('./feed.json', { cache: "no-store" });
  if (!res.ok) throw new Error(`Local feed not found`);

  const items = await res.json();
  DATA = items;

  els.status.textContent = "Latest Activity";
  apply();
}

// Init UI
els.q.addEventListener("input", apply);
els.pills.forEach(p => p.addEventListener("click", () => setFilter(p.dataset.filter)));

// Load feed
loadFeed().catch((err) => {
  console.error(err);
  els.status.textContent = "Couldn’t load activity.";
  els.results.hidden = true;
  els.empty.hidden = false;
});
